// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ckzxkYnDV5FN4h0JzJHT3AyPg2IGJTM',
    appId: '1:25785437905:web:803276b7480b4c2192bff0',
    messagingSenderId: '25785437905',
    projectId: 'soil-monitor-f5ed3',
    authDomain: 'soil-monitor-f5ed3.firebaseapp.com',
    databaseURL: 'https://soil-monitor-f5ed3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soil-monitor-f5ed3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhPyPqRqzqhVxrgT8Z-9GW4kPs_2Qf2DQ',
    appId: '1:25785437905:android:7abf14cf0f6f0f5792bff0',
    messagingSenderId: '25785437905',
    projectId: 'soil-monitor-f5ed3',
    databaseURL: 'https://soil-monitor-f5ed3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soil-monitor-f5ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3LI_U3TQNE39kqcid2JA_jBgX7eYNJ8',
    appId: '1:25785437905:ios:0e3fa6497b03aeb292bff0',
    messagingSenderId: '25785437905',
    projectId: 'soil-monitor-f5ed3',
    databaseURL: 'https://soil-monitor-f5ed3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soil-monitor-f5ed3.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz3LI_U3TQNE39kqcid2JA_jBgX7eYNJ8',
    appId: '1:25785437905:ios:0e3fa6497b03aeb292bff0',
    messagingSenderId: '25785437905',
    projectId: 'soil-monitor-f5ed3',
    databaseURL: 'https://soil-monitor-f5ed3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soil-monitor-f5ed3.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ckzxkYnDV5FN4h0JzJHT3AyPg2IGJTM',
    appId: '1:25785437905:web:72ff429e03cc244f92bff0',
    messagingSenderId: '25785437905',
    projectId: 'soil-monitor-f5ed3',
    authDomain: 'soil-monitor-f5ed3.firebaseapp.com',
    databaseURL: 'https://soil-monitor-f5ed3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soil-monitor-f5ed3.firebasestorage.app',
  );
}
